[package]
name = "zed-commands-context-server"
version = "0.1.0"
edition = "2021"
publish = false
license = "MIT"

[lib]
path = "src/extension.rs"
crate-type = ["cdylib"]

[dependencies]
serde = "1.0"
zed_extension_api = "0.2.0"
