id = "commands-context-server"
name = "Commands Context Server"
description = "Model Context Server for Commands (CLI)"
version = "0.0.1"
schema_version = 1
authors = ["Wes Higbee <wes.mcclure@gmail.com>"]
repository = "https://github.com/g0t4/zed-commands-context-server"

[context_servers.commands-context-server]
name = "Commands Context Server"
